import type { AppCategory, BuilderMode, Project } from "@/types";

// Canonical seed projects — the single source of truth for the store seed, the
// localStorage fallback (lib/backend.ts), and detail-page fallbacks. ids are
// `proj-1..6`. Previously this data was duplicated (and divergent) between the
// store and SAMPLE_PROJECTS; both now derive from here.
export const SEED_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "ClearPath Practice",
    icon: "Stethoscope",
    iconColor: "#0d9488",
    color: "#0d9488",
    category: "dashboard" as AppCategory,
    deploymentStatus: "live" as const,
    createdAt: BigInt(new Date("2026-01-15").getTime()),
    updatedAt: BigInt(new Date("2026-06-01").getTime()),
    answers: "{}",
    metadata: {
      maturity: "live" as const,
      tags: ["healthcare", "saas"],
      builderMode: "guided" as BuilderMode,
      priority: "high" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.4.1",
    linesOfCode: 3420,
    fileCount: 28,
    description:
      "Medical appointment scheduling and patient management platform",
    tags: ["healthcare", "saas"],
    burnRate: 340,
    burnRateBaseline: 320,
    burnRateStatus: "normal" as const,
    versionHistory: [
      {
        version: "1.0",
        timestamp: BigInt(new Date("2026-01-15").getTime()),
        changeSummary: "Initial release",
        specSnapshot: "{}",
      },
      {
        version: "1.1",
        timestamp: BigInt(new Date("2026-03-10").getTime()),
        changeSummary: "Patient portal improvements",
        specSnapshot: "{}",
      },
      {
        version: "1.2",
        timestamp: BigInt(new Date("2026-06-01").getTime()),
        changeSummary: "Scheduling engine v2",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: true,
    marketStatus: "published" as const,
    cloneCount: 47,
    verificationStatus: "verified" as const,
    updateCount: 3,
  },
  {
    id: "proj-2",
    name: "Community Hub",
    icon: "Users",
    iconColor: "#7c3aed",
    color: "#7c3aed",
    category: "social" as AppCategory,
    deploymentStatus: "live" as const,
    createdAt: BigInt(new Date("2026-02-10").getTime()),
    updatedAt: BigInt(new Date("2026-05-28").getTime()),
    answers: "{}",
    metadata: {
      // Was "building" while deploymentStatus is "live" — the contradiction
      // that made Community Hub show up in both Live and Building buckets.
      maturity: "live" as const,
      tags: ["social", "community"],
      builderMode: "guided" as BuilderMode,
      priority: "medium" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.3.0",
    linesOfCode: 5100,
    fileCount: 35,
    description:
      "Neighborhood social platform with events, groups, and local news",
    tags: ["social", "community"],
    burnRate: 520,
    burnRateBaseline: 480,
    burnRateStatus: "elevated" as const,
    versionHistory: [
      {
        version: "1.0",
        timestamp: BigInt(new Date("2026-02-10").getTime()),
        changeSummary: "Initial release",
        specSnapshot: "{}",
      },
      {
        version: "1.1",
        timestamp: BigInt(new Date("2026-04-20").getTime()),
        changeSummary: "Events feature",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: true,
    marketStatus: "published" as const,
    cloneCount: 12,
    verificationStatus: "pending" as const,
    updateCount: 2,
  },
  {
    id: "proj-3",
    name: "VaultEx Records",
    icon: "Shield",
    iconColor: "#ea580c",
    color: "#ea580c",
    category: "contentCms" as AppCategory,
    deploymentStatus: "notDeployed" as const,
    createdAt: BigInt(new Date("2026-03-05").getTime()),
    updatedAt: BigInt(new Date("2026-05-20").getTime()),
    answers: "{}",
    metadata: {
      maturity: "exploring" as const,
      tags: ["legal", "security"],
      builderMode: "standard" as BuilderMode,
      priority: "high" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.5.2",
    linesOfCode: 7800,
    fileCount: 42,
    description:
      "Secure digital vault for legal documents and records management",
    tags: ["legal", "security"],
    burnRate: 0,
    burnRateBaseline: 0,
    burnRateStatus: "normal" as const,
    versionHistory: [
      {
        version: "0.1",
        timestamp: BigInt(new Date("2026-03-05").getTime()),
        changeSummary: "Draft spec",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: false,
    marketStatus: "draft" as const,
    cloneCount: 0,
    verificationStatus: "unverified" as const,
    updateCount: 1,
  },
  {
    id: "proj-4",
    name: "TaskFlow Pro",
    icon: "CheckSquare",
    iconColor: "#2563eb",
    color: "#2563eb",
    category: "tracker" as AppCategory,
    deploymentStatus: "notDeployed" as const,
    createdAt: BigInt(new Date("2026-03-20").getTime()),
    updatedAt: BigInt(new Date("2026-06-05").getTime()),
    answers: "{}",
    metadata: {
      maturity: "building" as const,
      tags: ["productivity", "saas"],
      builderMode: "guided" as BuilderMode,
      priority: "medium" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.4.1",
    linesOfCode: 4200,
    fileCount: 31,
    description: "Team task management with automated workflows and reporting",
    tags: ["productivity", "saas"],
    burnRate: 0,
    burnRateBaseline: 0,
    burnRateStatus: "normal" as const,
    versionHistory: [
      {
        version: "0.1",
        timestamp: BigInt(new Date("2026-03-20").getTime()),
        changeSummary: "Initial wireframes",
        specSnapshot: "{}",
      },
      {
        version: "0.2",
        timestamp: BigInt(new Date("2026-05-10").getTime()),
        changeSummary: "Core task CRUD",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: false,
    marketStatus: "draft" as const,
    cloneCount: 0,
    verificationStatus: "unverified" as const,
    updateCount: 2,
  },
  {
    id: "proj-5",
    name: "BookEase",
    icon: "BookOpen",
    iconColor: "#d97706",
    color: "#d97706",
    category: "booking" as AppCategory,
    deploymentStatus: "notDeployed" as const,
    createdAt: BigInt(new Date("2026-04-12").getTime()),
    updatedAt: BigInt(new Date("2026-05-15").getTime()),
    answers: "{}",
    metadata: {
      maturity: "defining" as const,
      tags: ["education", "booking"],
      builderMode: "guided" as BuilderMode,
      priority: "low" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.3.0",
    linesOfCode: 2800,
    fileCount: 22,
    description: "Library booking and catalog system for small libraries",
    tags: ["education", "booking"],
    burnRate: 0,
    burnRateBaseline: 0,
    burnRateStatus: "normal" as const,
    versionHistory: [
      {
        version: "0.1",
        timestamp: BigInt(new Date("2026-04-12").getTime()),
        changeSummary: "Spec scaffolding",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: false,
    marketStatus: "draft" as const,
    cloneCount: 0,
    verificationStatus: "unverified" as const,
    updateCount: 1,
  },
  {
    id: "proj-6",
    name: "Giraffe",
    icon: "Zap",
    iconColor: "#16a34a",
    color: "#16a34a",
    category: "other" as AppCategory,
    deploymentStatus: "notDeployed" as const,
    createdAt: BigInt(new Date("2026-05-01").getTime()),
    updatedAt: BigInt(new Date("2026-06-08").getTime()),
    answers: "{}",
    metadata: {
      maturity: "idea" as const,
      tags: ["ai", "content"],
      builderMode: "guided" as BuilderMode,
      priority: "high" as const,
      attentionFlag: false,
    },
    caffeineVersion: "v2.5.2",
    linesOfCode: 6500,
    fileCount: 38,
    description: "AI-powered content discovery and recommendation platform",
    tags: ["ai", "content"],
    burnRate: 0,
    burnRateBaseline: 0,
    burnRateStatus: "normal" as const,
    versionHistory: [
      {
        version: "0.1",
        timestamp: BigInt(new Date("2026-05-01").getTime()),
        changeSummary: "Concept spec",
        specSnapshot: "{}",
      },
    ],
    specSections: [],
    marketAvailable: false,
    marketStatus: "draft" as const,
    cloneCount: 0,
    verificationStatus: "unverified" as const,
    updateCount: 1,
  },
];
